[package]
name = "dynamic-dependency-resolution-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.30", features = ["derive"] }
wasmtime = "30.0.1"
wasmtime-wasi = "30.0.1"
